#!/bin/sh

set -a
source /etc/environment.base
if [ -f /etc/environment ];then
source /etc/environment
fi

ulimit -c unlimited
ulimit -s 256

set +a
# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

ulimit -s 256

