#!/bin/sh

case "$1" in
  start)
        while read mod; do
            modprobe "$mod"
        done </etc/modules
	;;
  stop)
        tac /etc/modules | while read mod; do
            modprobe -r "$mod"
        done
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

