#!/bin/sh
#
case "$1" in
	start)
		[ -f /tmp/factory_mode ] && exit 1
		mkdir -p "$PERP_BASE" || exit 1
        cd "$PERP_BASE"
        chmod -t *
        perpboot -d
        ;;
    stop)
        killall -TERM perpboot
        ;;
    restart|reload)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
