#!/bin/sh
#
# netcheck
#

case "$1" in
  start)
        echo "Starting netcheck..."
	network_governor.sh &
        ;;
  stop)
        printf "Stopping netcheck..."
	killall network_governor.sh
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
